services:
  app:
    build:
      dockerfile: Dockerfile-dev
    command:  npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  node_modules: